// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/Evlushin/GophKeeper/internal/server/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSecret creates a new instance of MockSecret. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecret(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecret {
	mock := &MockSecret{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSecret is an autogenerated mock type for the Secret type
type MockSecret struct {
	mock.Mock
}

type MockSecret_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecret) EXPECT() *MockSecret_Expecter {
	return &MockSecret_Expecter{mock: &_m.Mock}
}

// CountSecret provides a mock function for the type MockSecret
func (_mock *MockSecret) CountSecret(ctx context.Context, indexSecret models.IndexSecret) (int64, error) {
	ret := _mock.Called(ctx, indexSecret)

	if len(ret) == 0 {
		panic("no return value specified for CountSecret")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexSecret) (int64, error)); ok {
		return returnFunc(ctx, indexSecret)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexSecret) int64); ok {
		r0 = returnFunc(ctx, indexSecret)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.IndexSecret) error); ok {
		r1 = returnFunc(ctx, indexSecret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecret_CountSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSecret'
type MockSecret_CountSecret_Call struct {
	*mock.Call
}

// CountSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - indexSecret models.IndexSecret
func (_e *MockSecret_Expecter) CountSecret(ctx interface{}, indexSecret interface{}) *MockSecret_CountSecret_Call {
	return &MockSecret_CountSecret_Call{Call: _e.mock.On("CountSecret", ctx, indexSecret)}
}

func (_c *MockSecret_CountSecret_Call) Run(run func(ctx context.Context, indexSecret models.IndexSecret)) *MockSecret_CountSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.IndexSecret
		if args[1] != nil {
			arg1 = args[1].(models.IndexSecret)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecret_CountSecret_Call) Return(n int64, err error) *MockSecret_CountSecret_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSecret_CountSecret_Call) RunAndReturn(run func(ctx context.Context, indexSecret models.IndexSecret) (int64, error)) *MockSecret_CountSecret_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecret provides a mock function for the type MockSecret
func (_mock *MockSecret) DeleteSecret(ctx context.Context, deleteSecret models.DeleteSecret) error {
	ret := _mock.Called(ctx, deleteSecret)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.DeleteSecret) error); ok {
		r0 = returnFunc(ctx, deleteSecret)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecret_DeleteSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecret'
type MockSecret_DeleteSecret_Call struct {
	*mock.Call
}

// DeleteSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - deleteSecret models.DeleteSecret
func (_e *MockSecret_Expecter) DeleteSecret(ctx interface{}, deleteSecret interface{}) *MockSecret_DeleteSecret_Call {
	return &MockSecret_DeleteSecret_Call{Call: _e.mock.On("DeleteSecret", ctx, deleteSecret)}
}

func (_c *MockSecret_DeleteSecret_Call) Run(run func(ctx context.Context, deleteSecret models.DeleteSecret)) *MockSecret_DeleteSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.DeleteSecret
		if args[1] != nil {
			arg1 = args[1].(models.DeleteSecret)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecret_DeleteSecret_Call) Return(err error) *MockSecret_DeleteSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecret_DeleteSecret_Call) RunAndReturn(run func(ctx context.Context, deleteSecret models.DeleteSecret) error) *MockSecret_DeleteSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecret provides a mock function for the type MockSecret
func (_mock *MockSecret) GetSecret(ctx context.Context, getSecret models.ShowSecret) (*models.SecretData, error) {
	ret := _mock.Called(ctx, getSecret)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 *models.SecretData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ShowSecret) (*models.SecretData, error)); ok {
		return returnFunc(ctx, getSecret)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ShowSecret) *models.SecretData); ok {
		r0 = returnFunc(ctx, getSecret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SecretData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.ShowSecret) error); ok {
		r1 = returnFunc(ctx, getSecret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecret_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type MockSecret_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - getSecret models.ShowSecret
func (_e *MockSecret_Expecter) GetSecret(ctx interface{}, getSecret interface{}) *MockSecret_GetSecret_Call {
	return &MockSecret_GetSecret_Call{Call: _e.mock.On("GetSecret", ctx, getSecret)}
}

func (_c *MockSecret_GetSecret_Call) Run(run func(ctx context.Context, getSecret models.ShowSecret)) *MockSecret_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ShowSecret
		if args[1] != nil {
			arg1 = args[1].(models.ShowSecret)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecret_GetSecret_Call) Return(secretData *models.SecretData, err error) *MockSecret_GetSecret_Call {
	_c.Call.Return(secretData, err)
	return _c
}

func (_c *MockSecret_GetSecret_Call) RunAndReturn(run func(ctx context.Context, getSecret models.ShowSecret) (*models.SecretData, error)) *MockSecret_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}

// IndexSecret provides a mock function for the type MockSecret
func (_mock *MockSecret) IndexSecret(ctx context.Context, indexSecret models.IndexSecret) ([]models.SecretData, error) {
	ret := _mock.Called(ctx, indexSecret)

	if len(ret) == 0 {
		panic("no return value specified for IndexSecret")
	}

	var r0 []models.SecretData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexSecret) ([]models.SecretData, error)); ok {
		return returnFunc(ctx, indexSecret)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexSecret) []models.SecretData); ok {
		r0 = returnFunc(ctx, indexSecret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.SecretData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.IndexSecret) error); ok {
		r1 = returnFunc(ctx, indexSecret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecret_IndexSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexSecret'
type MockSecret_IndexSecret_Call struct {
	*mock.Call
}

// IndexSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - indexSecret models.IndexSecret
func (_e *MockSecret_Expecter) IndexSecret(ctx interface{}, indexSecret interface{}) *MockSecret_IndexSecret_Call {
	return &MockSecret_IndexSecret_Call{Call: _e.mock.On("IndexSecret", ctx, indexSecret)}
}

func (_c *MockSecret_IndexSecret_Call) Run(run func(ctx context.Context, indexSecret models.IndexSecret)) *MockSecret_IndexSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.IndexSecret
		if args[1] != nil {
			arg1 = args[1].(models.IndexSecret)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecret_IndexSecret_Call) Return(secretDatas []models.SecretData, err error) *MockSecret_IndexSecret_Call {
	_c.Call.Return(secretDatas, err)
	return _c
}

func (_c *MockSecret_IndexSecret_Call) RunAndReturn(run func(ctx context.Context, indexSecret models.IndexSecret) ([]models.SecretData, error)) *MockSecret_IndexSecret_Call {
	_c.Call.Return(run)
	return _c
}

// StoreSecret provides a mock function for the type MockSecret
func (_mock *MockSecret) StoreSecret(ctx context.Context, storeSecret models.StoreSecret) error {
	ret := _mock.Called(ctx, storeSecret)

	if len(ret) == 0 {
		panic("no return value specified for StoreSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.StoreSecret) error); ok {
		r0 = returnFunc(ctx, storeSecret)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecret_StoreSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreSecret'
type MockSecret_StoreSecret_Call struct {
	*mock.Call
}

// StoreSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - storeSecret models.StoreSecret
func (_e *MockSecret_Expecter) StoreSecret(ctx interface{}, storeSecret interface{}) *MockSecret_StoreSecret_Call {
	return &MockSecret_StoreSecret_Call{Call: _e.mock.On("StoreSecret", ctx, storeSecret)}
}

func (_c *MockSecret_StoreSecret_Call) Run(run func(ctx context.Context, storeSecret models.StoreSecret)) *MockSecret_StoreSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.StoreSecret
		if args[1] != nil {
			arg1 = args[1].(models.StoreSecret)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecret_StoreSecret_Call) Return(err error) *MockSecret_StoreSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecret_StoreSecret_Call) RunAndReturn(run func(ctx context.Context, storeSecret models.StoreSecret) error) *MockSecret_StoreSecret_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSecret provides a mock function for the type MockSecret
func (_mock *MockSecret) UpdateSecret(ctx context.Context, updateSecret models.UpdateSecret) error {
	ret := _mock.Called(ctx, updateSecret)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UpdateSecret) error); ok {
		r0 = returnFunc(ctx, updateSecret)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecret_UpdateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSecret'
type MockSecret_UpdateSecret_Call struct {
	*mock.Call
}

// UpdateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - updateSecret models.UpdateSecret
func (_e *MockSecret_Expecter) UpdateSecret(ctx interface{}, updateSecret interface{}) *MockSecret_UpdateSecret_Call {
	return &MockSecret_UpdateSecret_Call{Call: _e.mock.On("UpdateSecret", ctx, updateSecret)}
}

func (_c *MockSecret_UpdateSecret_Call) Run(run func(ctx context.Context, updateSecret models.UpdateSecret)) *MockSecret_UpdateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.UpdateSecret
		if args[1] != nil {
			arg1 = args[1].(models.UpdateSecret)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecret_UpdateSecret_Call) Return(err error) *MockSecret_UpdateSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecret_UpdateSecret_Call) RunAndReturn(run func(ctx context.Context, updateSecret models.UpdateSecret) error) *MockSecret_UpdateSecret_Call {
	_c.Call.Return(run)
	return _c
}
