// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/Evlushin/GophKeeper/internal/client/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// DeleteSecret provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteSecret(ctx context.Context, req models.DeleteRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.DeleteRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecret'
type MockRepository_DeleteSecret_Call struct {
	*mock.Call
}

// DeleteSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - req models.DeleteRequest
func (_e *MockRepository_Expecter) DeleteSecret(ctx interface{}, req interface{}) *MockRepository_DeleteSecret_Call {
	return &MockRepository_DeleteSecret_Call{Call: _e.mock.On("DeleteSecret", ctx, req)}
}

func (_c *MockRepository_DeleteSecret_Call) Run(run func(ctx context.Context, req models.DeleteRequest)) *MockRepository_DeleteSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.DeleteRequest
		if args[1] != nil {
			arg1 = args[1].(models.DeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteSecret_Call) Return(err error) *MockRepository_DeleteSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteSecret_Call) RunAndReturn(run func(ctx context.Context, req models.DeleteRequest) error) *MockRepository_DeleteSecret_Call {
	_c.Call.Return(run)
	return _c
}

// ListSecret provides a mock function for the type MockRepository
func (_mock *MockRepository) ListSecret(ctx context.Context, req models.ListRequest) ([]models.SaveData, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListSecret")
	}

	var r0 []models.SaveData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ListRequest) ([]models.SaveData, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ListRequest) []models.SaveData); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.SaveData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.ListRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSecret'
type MockRepository_ListSecret_Call struct {
	*mock.Call
}

// ListSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - req models.ListRequest
func (_e *MockRepository_Expecter) ListSecret(ctx interface{}, req interface{}) *MockRepository_ListSecret_Call {
	return &MockRepository_ListSecret_Call{Call: _e.mock.On("ListSecret", ctx, req)}
}

func (_c *MockRepository_ListSecret_Call) Run(run func(ctx context.Context, req models.ListRequest)) *MockRepository_ListSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ListRequest
		if args[1] != nil {
			arg1 = args[1].(models.ListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ListSecret_Call) Return(saveDatas []models.SaveData, err error) *MockRepository_ListSecret_Call {
	_c.Call.Return(saveDatas, err)
	return _c
}

func (_c *MockRepository_ListSecret_Call) RunAndReturn(run func(ctx context.Context, req models.ListRequest) ([]models.SaveData, error)) *MockRepository_ListSecret_Call {
	_c.Call.Return(run)
	return _c
}

// ShowSecret provides a mock function for the type MockRepository
func (_mock *MockRepository) ShowSecret(ctx context.Context, req models.ShowRequest) (*models.ShowResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ShowSecret")
	}

	var r0 *models.ShowResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ShowRequest) (*models.ShowResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ShowRequest) *models.ShowResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ShowResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.ShowRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ShowSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowSecret'
type MockRepository_ShowSecret_Call struct {
	*mock.Call
}

// ShowSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - req models.ShowRequest
func (_e *MockRepository_Expecter) ShowSecret(ctx interface{}, req interface{}) *MockRepository_ShowSecret_Call {
	return &MockRepository_ShowSecret_Call{Call: _e.mock.On("ShowSecret", ctx, req)}
}

func (_c *MockRepository_ShowSecret_Call) Run(run func(ctx context.Context, req models.ShowRequest)) *MockRepository_ShowSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ShowRequest
		if args[1] != nil {
			arg1 = args[1].(models.ShowRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ShowSecret_Call) Return(showResponse *models.ShowResponse, err error) *MockRepository_ShowSecret_Call {
	_c.Call.Return(showResponse, err)
	return _c
}

func (_c *MockRepository_ShowSecret_Call) RunAndReturn(run func(ctx context.Context, req models.ShowRequest) (*models.ShowResponse, error)) *MockRepository_ShowSecret_Call {
	_c.Call.Return(run)
	return _c
}

// StoreSecret provides a mock function for the type MockRepository
func (_mock *MockRepository) StoreSecret(ctx context.Context, req models.StoreRequest) (*models.SaveData, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for StoreSecret")
	}

	var r0 *models.SaveData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.StoreRequest) (*models.SaveData, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.StoreRequest) *models.SaveData); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SaveData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.StoreRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_StoreSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreSecret'
type MockRepository_StoreSecret_Call struct {
	*mock.Call
}

// StoreSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - req models.StoreRequest
func (_e *MockRepository_Expecter) StoreSecret(ctx interface{}, req interface{}) *MockRepository_StoreSecret_Call {
	return &MockRepository_StoreSecret_Call{Call: _e.mock.On("StoreSecret", ctx, req)}
}

func (_c *MockRepository_StoreSecret_Call) Run(run func(ctx context.Context, req models.StoreRequest)) *MockRepository_StoreSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.StoreRequest
		if args[1] != nil {
			arg1 = args[1].(models.StoreRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_StoreSecret_Call) Return(saveData *models.SaveData, err error) *MockRepository_StoreSecret_Call {
	_c.Call.Return(saveData, err)
	return _c
}

func (_c *MockRepository_StoreSecret_Call) RunAndReturn(run func(ctx context.Context, req models.StoreRequest) (*models.SaveData, error)) *MockRepository_StoreSecret_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSecret provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateSecret(ctx context.Context, req models.UpdateRequest) (*models.SaveData, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecret")
	}

	var r0 *models.SaveData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UpdateRequest) (*models.SaveData, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UpdateRequest) *models.SaveData); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SaveData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.UpdateRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_UpdateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSecret'
type MockRepository_UpdateSecret_Call struct {
	*mock.Call
}

// UpdateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - req models.UpdateRequest
func (_e *MockRepository_Expecter) UpdateSecret(ctx interface{}, req interface{}) *MockRepository_UpdateSecret_Call {
	return &MockRepository_UpdateSecret_Call{Call: _e.mock.On("UpdateSecret", ctx, req)}
}

func (_c *MockRepository_UpdateSecret_Call) Run(run func(ctx context.Context, req models.UpdateRequest)) *MockRepository_UpdateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.UpdateRequest
		if args[1] != nil {
			arg1 = args[1].(models.UpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateSecret_Call) Return(saveData *models.SaveData, err error) *MockRepository_UpdateSecret_Call {
	_c.Call.Return(saveData, err)
	return _c
}

func (_c *MockRepository_UpdateSecret_Call) RunAndReturn(run func(ctx context.Context, req models.UpdateRequest) (*models.SaveData, error)) *MockRepository_UpdateSecret_Call {
	_c.Call.Return(run)
	return _c
}
