// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/Evlushin/GophKeeper/internal/server/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CountSecret provides a mock function for the type MockRepository
func (_mock *MockRepository) CountSecret(ctx context.Context, indexSecret models.IndexSecret) (int64, error) {
	ret := _mock.Called(ctx, indexSecret)

	if len(ret) == 0 {
		panic("no return value specified for CountSecret")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexSecret) (int64, error)); ok {
		return returnFunc(ctx, indexSecret)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexSecret) int64); ok {
		r0 = returnFunc(ctx, indexSecret)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.IndexSecret) error); ok {
		r1 = returnFunc(ctx, indexSecret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CountSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSecret'
type MockRepository_CountSecret_Call struct {
	*mock.Call
}

// CountSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - indexSecret models.IndexSecret
func (_e *MockRepository_Expecter) CountSecret(ctx interface{}, indexSecret interface{}) *MockRepository_CountSecret_Call {
	return &MockRepository_CountSecret_Call{Call: _e.mock.On("CountSecret", ctx, indexSecret)}
}

func (_c *MockRepository_CountSecret_Call) Run(run func(ctx context.Context, indexSecret models.IndexSecret)) *MockRepository_CountSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.IndexSecret
		if args[1] != nil {
			arg1 = args[1].(models.IndexSecret)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CountSecret_Call) Return(n int64, err error) *MockRepository_CountSecret_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_CountSecret_Call) RunAndReturn(run func(ctx context.Context, indexSecret models.IndexSecret) (int64, error)) *MockRepository_CountSecret_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecret provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteSecret(ctx context.Context, deleteSecret models.DeleteSecret) error {
	ret := _mock.Called(ctx, deleteSecret)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.DeleteSecret) error); ok {
		r0 = returnFunc(ctx, deleteSecret)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecret'
type MockRepository_DeleteSecret_Call struct {
	*mock.Call
}

// DeleteSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - deleteSecret models.DeleteSecret
func (_e *MockRepository_Expecter) DeleteSecret(ctx interface{}, deleteSecret interface{}) *MockRepository_DeleteSecret_Call {
	return &MockRepository_DeleteSecret_Call{Call: _e.mock.On("DeleteSecret", ctx, deleteSecret)}
}

func (_c *MockRepository_DeleteSecret_Call) Run(run func(ctx context.Context, deleteSecret models.DeleteSecret)) *MockRepository_DeleteSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.DeleteSecret
		if args[1] != nil {
			arg1 = args[1].(models.DeleteSecret)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteSecret_Call) Return(err error) *MockRepository_DeleteSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteSecret_Call) RunAndReturn(run func(ctx context.Context, deleteSecret models.DeleteSecret) error) *MockRepository_DeleteSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecret provides a mock function for the type MockRepository
func (_mock *MockRepository) GetSecret(ctx context.Context, getSecret models.ShowSecret) (*models.SecretData, error) {
	ret := _mock.Called(ctx, getSecret)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 *models.SecretData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ShowSecret) (*models.SecretData, error)); ok {
		return returnFunc(ctx, getSecret)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ShowSecret) *models.SecretData); ok {
		r0 = returnFunc(ctx, getSecret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SecretData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.ShowSecret) error); ok {
		r1 = returnFunc(ctx, getSecret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type MockRepository_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - getSecret models.ShowSecret
func (_e *MockRepository_Expecter) GetSecret(ctx interface{}, getSecret interface{}) *MockRepository_GetSecret_Call {
	return &MockRepository_GetSecret_Call{Call: _e.mock.On("GetSecret", ctx, getSecret)}
}

func (_c *MockRepository_GetSecret_Call) Run(run func(ctx context.Context, getSecret models.ShowSecret)) *MockRepository_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ShowSecret
		if args[1] != nil {
			arg1 = args[1].(models.ShowSecret)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetSecret_Call) Return(secretData *models.SecretData, err error) *MockRepository_GetSecret_Call {
	_c.Call.Return(secretData, err)
	return _c
}

func (_c *MockRepository_GetSecret_Call) RunAndReturn(run func(ctx context.Context, getSecret models.ShowSecret) (*models.SecretData, error)) *MockRepository_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}

// IndexSecret provides a mock function for the type MockRepository
func (_mock *MockRepository) IndexSecret(ctx context.Context, indexSecret models.IndexSecret) ([]models.SecretData, error) {
	ret := _mock.Called(ctx, indexSecret)

	if len(ret) == 0 {
		panic("no return value specified for IndexSecret")
	}

	var r0 []models.SecretData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexSecret) ([]models.SecretData, error)); ok {
		return returnFunc(ctx, indexSecret)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexSecret) []models.SecretData); ok {
		r0 = returnFunc(ctx, indexSecret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.SecretData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.IndexSecret) error); ok {
		r1 = returnFunc(ctx, indexSecret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_IndexSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexSecret'
type MockRepository_IndexSecret_Call struct {
	*mock.Call
}

// IndexSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - indexSecret models.IndexSecret
func (_e *MockRepository_Expecter) IndexSecret(ctx interface{}, indexSecret interface{}) *MockRepository_IndexSecret_Call {
	return &MockRepository_IndexSecret_Call{Call: _e.mock.On("IndexSecret", ctx, indexSecret)}
}

func (_c *MockRepository_IndexSecret_Call) Run(run func(ctx context.Context, indexSecret models.IndexSecret)) *MockRepository_IndexSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.IndexSecret
		if args[1] != nil {
			arg1 = args[1].(models.IndexSecret)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_IndexSecret_Call) Return(secretDatas []models.SecretData, err error) *MockRepository_IndexSecret_Call {
	_c.Call.Return(secretDatas, err)
	return _c
}

func (_c *MockRepository_IndexSecret_Call) RunAndReturn(run func(ctx context.Context, indexSecret models.IndexSecret) ([]models.SecretData, error)) *MockRepository_IndexSecret_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockRepository
func (_mock *MockRepository) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockRepository_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) Ping(ctx interface{}) *MockRepository_Ping_Call {
	return &MockRepository_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockRepository_Ping_Call) Run(run func(ctx context.Context)) *MockRepository_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Ping_Call) Return(err error) *MockRepository_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockRepository_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// StoreSecret provides a mock function for the type MockRepository
func (_mock *MockRepository) StoreSecret(ctx context.Context, storeSecret models.StoreSecret) error {
	ret := _mock.Called(ctx, storeSecret)

	if len(ret) == 0 {
		panic("no return value specified for StoreSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.StoreSecret) error); ok {
		r0 = returnFunc(ctx, storeSecret)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_StoreSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreSecret'
type MockRepository_StoreSecret_Call struct {
	*mock.Call
}

// StoreSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - storeSecret models.StoreSecret
func (_e *MockRepository_Expecter) StoreSecret(ctx interface{}, storeSecret interface{}) *MockRepository_StoreSecret_Call {
	return &MockRepository_StoreSecret_Call{Call: _e.mock.On("StoreSecret", ctx, storeSecret)}
}

func (_c *MockRepository_StoreSecret_Call) Run(run func(ctx context.Context, storeSecret models.StoreSecret)) *MockRepository_StoreSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.StoreSecret
		if args[1] != nil {
			arg1 = args[1].(models.StoreSecret)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_StoreSecret_Call) Return(err error) *MockRepository_StoreSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_StoreSecret_Call) RunAndReturn(run func(ctx context.Context, storeSecret models.StoreSecret) error) *MockRepository_StoreSecret_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSecret provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateSecret(ctx context.Context, updateSecret models.UpdateSecret) error {
	ret := _mock.Called(ctx, updateSecret)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UpdateSecret) error); ok {
		r0 = returnFunc(ctx, updateSecret)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSecret'
type MockRepository_UpdateSecret_Call struct {
	*mock.Call
}

// UpdateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - updateSecret models.UpdateSecret
func (_e *MockRepository_Expecter) UpdateSecret(ctx interface{}, updateSecret interface{}) *MockRepository_UpdateSecret_Call {
	return &MockRepository_UpdateSecret_Call{Call: _e.mock.On("UpdateSecret", ctx, updateSecret)}
}

func (_c *MockRepository_UpdateSecret_Call) Run(run func(ctx context.Context, updateSecret models.UpdateSecret)) *MockRepository_UpdateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.UpdateSecret
		if args[1] != nil {
			arg1 = args[1].(models.UpdateSecret)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateSecret_Call) Return(err error) *MockRepository_UpdateSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateSecret_Call) RunAndReturn(run func(ctx context.Context, updateSecret models.UpdateSecret) error) *MockRepository_UpdateSecret_Call {
	_c.Call.Return(run)
	return _c
}
